export const enum ERROR_CODES {
  TIME_LIMIT_FOR_LIKES = 'LIKE_LIMIT',
  ALREADY_LIKED_THIS_EMPLOYEE = 'ONE_LIKE_PER_EMPLOYEE',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  RESOURCE_LOCKED_EXCEPTION = 'RESOURCE_LOCKED_EXCEPTION',
  USER_FRIENDLY_MESSAGE = 'USER_FRIENDLY_MESSAGE'
}
